[package]
name = "postgres_large_object"
version = "0.2.0"
authors = ["Steven Fackler <sfackler@gmail.com>"]
license = "MIT"
description = "Large object support for rust-postgres"
repository = "https://github.com/sfackler/rust-postgres-large-object"
documentation = "https://sfackler.github.io/rust-postgres-large-object/doc/postgres_large_object"
readme = "README.md"
keywords = ["database", "sql", "postgres"]

[dependencies]
postgres = "0.8"
